//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignatureCellType {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignatureCellType.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string SignatureCellType_DisplayName {
            get {
                return ResourceManager.GetString("SignatureCellType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotSize.
        /// </summary>
        internal static string SignatureCellType_DotSize {
            get {
                return ResourceManager.GetString("SignatureCellType_DotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius of a single dot..
        /// </summary>
        internal static string SignatureCellType_DotSize_Description {
            get {
                return ResourceManager.GetString("SignatureCellType_DotSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDisabled.
        /// </summary>
        internal static string SignatureCellType_IsDisabled {
            get {
                return ResourceManager.GetString("SignatureCellType_IsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineMaxWidth.
        /// </summary>
        internal static string SignatureCellType_LineMaxWidth {
            get {
                return ResourceManager.GetString("SignatureCellType_LineMaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum width of a line..
        /// </summary>
        internal static string SignatureCellType_LineMaxWidth_Description {
            get {
                return ResourceManager.GetString("SignatureCellType_LineMaxWidth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineMinWidth.
        /// </summary>
        internal static string SignatureCellType_LineMinWidth {
            get {
                return ResourceManager.GetString("SignatureCellType_LineMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum width of a line..
        /// </summary>
        internal static string SignatureCellType_LineMinWidth_Description {
            get {
                return ResourceManager.GetString("SignatureCellType_LineMinWidth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string SignatureCellType_Options {
            get {
                return ResourceManager.GetString("SignatureCellType_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string SignatureCellType_Others {
            get {
                return ResourceManager.GetString("SignatureCellType_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string SignatureCellType_Page_ClearButtonText {
            get {
                return ResourceManager.GetString("SignatureCellType_Page_ClearButtonText", resourceCulture);
            }
        }
    }
}
